### ISSUE TITLE
Use better naming convention for files

### ISSUE THREAD

**Issue by sebamarynissen** [sebamarynissen/simtropolis-channel#42]
Imagine the following situation. Someone uploads a file to the STEX and includes an empty `metadata.yaml`. This will generate a file `src/yaml/author/slugified-title.yaml`.

Now imagine the creator changes the title on the STEX later on, which would cause an additional `src/yaml/new-title.yaml` to be created, but that would cause assets to be defined twice - and hence fail the linting.

I therefore plan to change the naming convention of the files. Instead of grouping files in folders by author, we'll change this to a flat structure where every file starts with the file id on the STEX, followed by the slugified title. The PR generating action will subsequently check whether a file with this file id already exists, and if so delete it if it has a different name. This would then cause git to recognize it as a file being renamed if the changes are small.

This approach has the benefit that files are uniquely identified by their id, but they can still be easily discovered in modern IDE's using - e.g. `Ctrl + P` in Sublime Text.

As an optimization, we might still group the files in folders, but not by author, but by file id range so that we avoid a single folder of tens of thousands of files. This is by the way also the approach that git takes for the `.git` folder: the first two characters of the commit hash are used as folder name.

@memo33 do you have any additional ideas or remarks for this? Obviously we have to educate users that renaming a package after it has already been published on the channel is a very bad idea, but I think we should still support it.

**Comment by memo33** [comment]
That's a good point, really. I agree it makes sense to include the STEX ID in the file names to ensure uniqueness.

Considering that some manual editing operations might still be performed on this repository, I think a file structure like `USERNAME/STEXTITLE_ID.yaml` would be easier to work with. Unlike git, we don't need to optimize "looking up files based on ID". (Actually, I guess manual edits would be kept to a minimum, as there's a chance the bot would overwrite them.)

As for renaming packages, that's indeed a problem. Perhaps, when the STEX title is changed, you could stick to the original package name, regardless - mainly as a safeguard against unintentional renaming. If renaming the package is intentional, it could be done explicitly in the metadata.

**Comment by sebamarynissen** [comment]
Okay, I think I'm going to go with a structure `username/id-stextitle.yaml`. This

- Keeps the amount of files in the `src/yaml` limited, as it's one folder per user.
- Makes it relatively easy to perform a manual lookup of a file.
- Ensures a nice sort order in the folders because the files will be sorted in order of upload date.

If a user decides to rename a package - for example `aaron-graham:gracie-manor` to `nybt:gracie-manor`, the file won't be moved to another folder. It will always be kept in the folder of the STEX user that uploaded it. The extreme case of a user changing their username, or the ST admins moving an upload to a different user - as they have done with a few of Pegasus' uploads iirc - is ignored and can probably be handled manually if needed.

That's not a bad idea actually to keep the name of the initial upload, unless explicitly overridden by the metadata. So basically, the fetch action will check if a file already existed or not by looking up the file by username and file id. If it finds an existing file, then it makes sure the name of the package is not changed, but it will change the *filename* if that differs.

I could probably add some heuristics to this as well, such as stripping out version from the stex title, such as `Mega Prop Pack v1` -> `mega-prop-pack`. Open question with this case: what should happen when that user decides to release v2 of the prop pack as a separate upload? In that case two packages with the same name would exist, although that is probably handled nicely by the sort order of the files, meaning that it's the last file in the folder that gets precedence when building the channel.

**Comment by memo33** [comment]
If two packages with the same name exist, the linter should fail. I think this is sufficiently unlikely that we can just sort out those cases manually. The usual reason for creating a second STEX entry is that the author wants to keep the original around unchanged, probably due to backward incompatible changes, such as assigning new IIDs. In such cases, it makes sense to have  two packages as well.

**Comment by sebamarynissen** [comment]
Alright. In that case I will just keep the stex title verbatim, and then we'll just have to educate users that they should never put the version in the title, unless they plan to specifically override the name of their package in `metadata.yaml`.

**Comment by sebamarynissen** [comment]
Fixed in #44.
